// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6033.RobotCodeJava2018.subsystems;

import java.util.concurrent.TimeUnit;

import org.usfirst.frc6033.RobotCodeJava2018.RobotMap;
import org.usfirst.frc6033.RobotCodeJava2018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.interfaces.Potentiometer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Elevator extends Subsystem {

	/*
	public final double outerUpLimit = 31.0;
	public final double outerDownLimit =  0.5;
	
	public final double innerUpLimit = 35.7;
	public final double innerDownLimit = 0.5;
	*/

	

	public final double outerUpLimit = 999;
	public final double outerDownLimit =  -999;
	
	public final double innerUpLimit = 999;
	public final double innerDownLimit = -999;

	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private final SpeedController innerSection = RobotMap.elevatorInnerSection;
	private final SpeedController outerSection = RobotMap.elevatorOuterSection;
	private final Encoder innerSectionEncoder = RobotMap.elevatorInnerSectionEncoder;
	private final Encoder outerSectionEncoder = RobotMap.elevatorOuterSectionEncoder;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	@Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	public void setInnerMotor(double power) {
		innerSection.set(power);
	}
	
	public void stopInnerMotor()
	{
		innerSection.stopMotor();
	}
	
	public void stopOuterMotor()
	{
		outerSection.stopMotor();
	}

	public void setOuterMotor(double power) {
		outerSection.set(power);
	}

	public double getDistanceInnerSectionEncoder() {
		return this.innerSectionEncoder.getDistance();
	}

	public double getDistanceOuterSectionEncoder() {
		return this.outerSectionEncoder.getDistance();
	}

	public double getHeight() {
		return (getDistanceInnerSectionEncoder() + getDistanceOuterSectionEncoder());
	}

	public void resetEncoders() {
		this.innerSectionEncoder.reset();
		this.outerSectionEncoder.reset();
	}
}
