// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6033.RobotCodeJava2018.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc6033.RobotCodeJava2018.Robot;

/**
 *
 */
public class DriveReturnToSetHeading extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	private double initialAngle;
	private double targetHeading;
	private double m_degrees;
	private static double minTurn = .1;
	private int m_direction;
	private double currentHeading;
	private double degreesRemaining = 999;
	static final double decelDegrees = 10;
	static final double minDecelSpeed = 0.20;
	static final double angleTolerance = 0.05;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public DriveReturnToSetHeading() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.drive);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		initialAngle = Robot.drive.getGyroAngle();
		targetHeading = Robot.drive.getSavedHeading();
		currentHeading = Robot.drive.getGyroAngle();

		if (targetHeading > initialAngle) {
			m_degrees = targetHeading - initialAngle;
			m_direction = Robot.drive.DirectionRight;
		} else {
			m_degrees = initialAngle - targetHeading;
			m_direction = Robot.drive.DirectionLeft;
		}
		setTimeout(1);
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {
		initialAngle = Robot.drive.getGyroAngle();
		targetHeading = Robot.drive.getSavedHeading();
		currentHeading = Robot.drive.getGyroAngle();

		if (targetHeading > initialAngle) {
			m_degrees = targetHeading - initialAngle;
			m_direction = Robot.drive.DirectionRight;
		} else {
			m_degrees = initialAngle - targetHeading;
			m_direction = Robot.drive.DirectionLeft;
		}
	}

	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() {
		currentHeading = Robot.drive.getGyroAngle();
		degreesRemaining = (targetHeading - currentHeading) * m_direction;

		double calcSpeed = getSpeedDecel(degreesRemaining);
		Robot.drive.Turn(calcSpeed, m_direction);
	}

	private double getSpeedDecel(double degreesRemaining) {
		double newSpeed = Robot.AutoTurnSpeed;
		double tmpSpeed = 0;
		if (degreesRemaining < decelDegrees) {
			if (newSpeed > minDecelSpeed) {
				tmpSpeed = degreesRemaining / decelDegrees * (1 - minDecelSpeed) + minDecelSpeed;
				if (newSpeed > tmpSpeed)
					newSpeed = tmpSpeed;
			}
		}
		return newSpeed;
	}

	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished() {
		if (Math.abs(targetHeading - initialAngle) < minTurn) {

			return true;
		}
		if (degreesRemaining - angleTolerance <= 0) {

			return true;
		}

		if (this.isTimedOut()) {

			return true;
		}
		return false;
	}

	// Called once after isFinished returns true
	@Override
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted() {
	}
}
